name: Makefile CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build dos app
      run: make  ms-dos

    - name: build mbr boot 
      run: make  boot-mbr
